name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el código
        uses: actions/checkout@v3

      - name: Desplegar en el servidor remoto
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}  # IP o dominio del servidor
          username: ${{ secrets.SERVER_USER }}  # Usuario SSH
          key: ${{ secrets.SERVER_SSH_KEY }}  # Clave privada SSH
          script: |
            cd /home/unizar
            rm -rf backend
            git clone https://github.com/UNIZAR-30226-2025-09/backend.git
            cd backend/docker
            bash hard_reset_sin_guion.sh
