name: Test Backend

on:
  workflow_run:
    workflows: ["Deploy Backend"]  # Nombre del workflow anterior
    types:
      - completed  # Opciones: requested, completed
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el código
        uses: actions/checkout@v3

      - name: Ejecutar tests en servidor remoto
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
                      
            echo "Entrando a backend..."
            cd /home/unizar/backend

            npm install
    
            echo "Ejecutando todos los tests"
            npm run test
